* RULES

  https://en.wikipedia.org/wiki/Stratego#Gameplay

** GAMEPLAY

   Players alternate moving; red moves first. Each player moves one piece per turn. A player must move a piece in his turn; there is no "pass" (like that in the game of go).

   Two zones in the middle of the board, each 2×2, cannot be entered by either player's pieces at any time. They are shown as lakes on the battlefield and serve as choke points to make frontal assaults less direct.

   The game can be won by capturing the opponent's Flag, or all of his moveable pieces. Note that it is possible to have ranked pieces that are not moveable because they are trapped behind bombs. There are several ways in which a draw can effectively result (though the rules do not indicate that a draw is a possible outcome):

   - each Flag is surrounded by bombs and neither player has a miner, and there are insufficient number of moveable pieces or of insufficient rank for either player to corner and capture all of the opponent's moveable pieces;
   - an opponent's Flag is exposed, but the player has only one moveable piece, the opponent has only one moveable piece but of a higher rank and it guards the Flag, so that it is impossible for the player to either capture the Flag or the higher ranked piece;
   - there are a few "indian stand-off" situations, where one or more pairs of pieces shuffle around endlessly in order to maintain some advantage or prevent some advantage by the opponent, and no progress can be made;
   - It is possible for both players to have one mobile piece remaining, and they are of equal rank. If one piece strikes the other, both are removed, leaving no mobile pieces on the board. This may be defined as a draw.

   The average game has 381 moves. The number of legal positions is 10115. The number of possible games is 10535.[4] Stratego has many more moves and substantially greater complexity than other familiar games like Chess, Go and Backgammon. However unlike those games where a single bad move at any point may result in loss of the game, most moves in Stratego are inconsequential.

** RULES OF MOVEMENT

   All movable pieces, with the exception of the Scout, may move only one step to any adjacent space vertically or horizontally (but not diagonally). A piece may not move onto a space occupied by a like color piece. Bomb and Flag pieces are not moveable. The Scout may move any number of spaces in a straight line (such as the rook in chess). In the older versions of Stratego the Scout could not move and strike in the same turn; in newer versions this was allowed. Even before that, sanctioned play usually amended the original Scout movement to allow moving and striking in the same turn because it facilitates gameplay. No piece can move back and forth between the same two spaces for more than three consecutive turns (two square rule), nor can a piece endlessly chase a piece it has no hope of capturing (more square rule).

   When the player wants to attack, they move their piece onto a square occupied by an opposing piece. Both players then reveal their piece's rank; the weaker piece (see exceptions below) is removed from the board. If the engaging pieces are of equal rank, both are removed. A piece may not move onto a square already occupied unless it attacks. Two pieces have special attack powers. One special piece is the Bomb which only Miners can defuse. It immediately eliminates any other piece striking it, without itself being destroyed. Each player also has one Spy, which succeeds only if it attacks the Marshal, or the Flag. If the Spy attacks any other piece, or is attacked by any piece (including the Marshal), the Spy is defeated. The original rules contained a provision that following a strike, the winning piece immediately occupies the space vacated by the losing piece. This makes sense when the winning piece belongs to the player on move, but no sense when the winning piece belongs to the player not on move. The latter part of the rule has been quietly ignored in most play.

** RECORDING

   Competitive play does not include recording the game, unlike Chess. The game is fast-paced, no standard notation exists, and players keep their initial setups secret, so recording over-the-board games is impractical. However, digital interfaces like web-based gaming interfaces, may have a facility for recording, replaying and downloading the game. Those interfaces use an algebraic style notation that numbers the rows ('ranks') 1 to 10 from bottom to top and the columns ('files') A to J from left to right. Alternately, a few interfaces designate the files as A to K, omitting 'I'. Moves are recorded as source square followed by destination square separated by a "-" (move) or "x" (strike). Revealed pieces on strikes precede the square designation, and may be by either rank name or rank number for brevity, for example "major B2xcaptain B3". The bottom half of the board is by default considered to be the 'red' side, and the top half the 'blue' side.

   No published compilation of recorded exemplary games (akin to master games in chess) exists.

** PIECES

   Classic pieces

   There are seven immobile pieces - six Bombs and one Flag - and 33 ranked mobile pieces per player. From highest rank to lowest the pieces are:

   | Rank    | Piece          | No. | Special properties                                                            |
   |---------+----------------+-----+-------------------------------------------------------------------------------|
   | B       | Bomb           |   6 | Immovable; defeats any attacking piece except Miner                           |
   | 10 or 1 | Marshall       |   1 | Can be captured by the Spy                                                    |
   | 9 or 2  | General        |   1 |                                                                               |
   | 8 or 3  | Colonel        |   2 |                                                                               |
   | 7 or 4  | Major          |   3 |                                                                               |
   | 6 or 5  | Captain        |   4 |                                                                               |
   | 5 or 6  | Lieutenant     |   4 |                                                                               |
   | 4 or 7  | Sergeant       |   4 |                                                                               |
   | 3 or 8  | Miner / Sapper |   5 | Can defuse bombs                                                              |
   | 2 or 9  | Scout          |   8 | Can move any distance in a straight line, without leaping over pieces / lakes |
   | 1 or S  | Spy            |   1 | Can defeat the Marshal, but only if the Spy makes the attack                  |
   | F       | Flag           |   1 | Immovable; its capture ends the game                                          |

   Some versions (primarily those released since 2000) make 10 (the Marshal) the highest rank with the Spy ranked 1, while others (versions prior to 2000, as well as the Nostalgia version released in 2002) have the Marshal piece ranked at 1 and the Spy designated S.
